In [36]:
from sklearn.datasets import load_breast_cancer

from sklearn.preprocessing import StandardScaler

import pandas as pd
import numpy as np

from keras.models import Sequential
from keras.layers import Dense


In [3]:
data = load_breast_cancer()

In [4]:
data

{'DESCR': '.. _breast_cancer_dataset:\n\nBreast cancer wisconsin (diagnostic) dataset\n--------------------------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 569\n\n    :Number of Attributes: 30 numeric, predictive attributes and the class\n\n    :Attribute Information:\n        - radius (mean of distances from center to points on the perimeter)\n        - texture (standard deviation of gray-scale values)\n        - perimeter\n        - area\n        - smoothness (local variation in radius lengths)\n        - compactness (perimeter^2 / area - 1.0)\n        - concavity (severity of concave portions of the contour)\n        - concave points (number of concave portions of the contour)\n        - symmetry \n        - fractal dimension ("coastline approximation" - 1)\n\n        The mean, standard error, and "worst" or largest (mean of the three\n        largest values) of these features were computed for each image,\n        resulting in 30 features.  For

In [5]:
data.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [6]:
print(data['DESCR'])

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry 
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 3 is Mean Radius, f

In [7]:
print(data['data'])

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


In [8]:
data['data'].shape

(569, 30)

In [9]:
data['feature_names']

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [10]:
data['data'][1]

array([2.057e+01, 1.777e+01, 1.329e+02, 1.326e+03, 8.474e-02, 7.864e-02,
       8.690e-02, 7.017e-02, 1.812e-01, 5.667e-02, 5.435e-01, 7.339e-01,
       3.398e+00, 7.408e+01, 5.225e-03, 1.308e-02, 1.860e-02, 1.340e-02,
       1.389e-02, 3.532e-03, 2.499e+01, 2.341e+01, 1.588e+02, 1.956e+03,
       1.238e-01, 1.866e-01, 2.416e-01, 1.860e-01, 2.750e-01, 8.902e-02])

In [11]:
j=0
for i in data['feature_names']:
  print(i,":",data['data'][1][j])
  j+=1

mean radius : 20.57
mean texture : 17.77
mean perimeter : 132.9
mean area : 1326.0
mean smoothness : 0.08474
mean compactness : 0.07864
mean concavity : 0.0869
mean concave points : 0.07017
mean symmetry : 0.1812
mean fractal dimension : 0.05667
radius error : 0.5435
texture error : 0.7339
perimeter error : 3.398
area error : 74.08
smoothness error : 0.005225
compactness error : 0.01308
concavity error : 0.0186
concave points error : 0.0134
symmetry error : 0.01389
fractal dimension error : 0.003532
worst radius : 24.99
worst texture : 23.41
worst perimeter : 158.8
worst area : 1956.0
worst smoothness : 0.1238
worst compactness : 0.1866
worst concavity : 0.2416
worst concave points : 0.186
worst symmetry : 0.275
worst fractal dimension : 0.08902


In [12]:
data['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [13]:
data['target_names']

array(['malignant', 'benign'], dtype='<U9')

In [14]:
data['target'].shape

(569,)

In [15]:
data['filename']

'/usr/local/lib/python3.7/dist-packages/sklearn/datasets/data/breast_cancer.csv'

In [16]:
feature=data['data']

In [17]:
label=data['target']

In [18]:
feature.shape

(569, 30)

In [19]:
label

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [20]:
scale = StandardScaler()
feature = scale.fit_transform(feature)

In [21]:
j=0
for i in data['feature_names']:
  print(i,":",feature[0][j])
  j+=1

mean radius : 1.0970639814699807
mean texture : -2.0733350146975935
mean perimeter : 1.2699336881399383
mean area : 0.9843749048031144
mean smoothness : 1.568466329243428
mean compactness : 3.2835146709868264
mean concavity : 2.652873983743168
mean concave points : 2.532475216403245
mean symmetry : 2.2175150059646405
mean fractal dimension : 2.255746885296269
radius error : 2.4897339267376193
texture error : -0.5652650590684639
perimeter error : 2.833030865855184
area error : 2.4875775569611043
smoothness error : -0.21400164666895383
compactness error : 1.3168615683959484
concavity error : 0.72402615808036
concave points error : 0.6608199414286064
symmetry error : 1.1487566671861758
fractal dimension error : 0.9070830809973359
worst radius : 1.8866896251792757
worst texture : -1.3592934737640827
worst perimeter : 2.3036006236225606
worst area : 2.0012374893299207
worst smoothness : 1.3076862710715387
worst compactness : 2.616665023512603
worst concavity : 2.1095263465722556
worst conca

In [22]:
feature[0]

array([ 1.09706398, -2.07333501,  1.26993369,  0.9843749 ,  1.56846633,
        3.28351467,  2.65287398,  2.53247522,  2.21751501,  2.25574689,
        2.48973393, -0.56526506,  2.83303087,  2.48757756, -0.21400165,
        1.31686157,  0.72402616,  0.66081994,  1.14875667,  0.90708308,
        1.88668963, -1.35929347,  2.30360062,  2.00123749,  1.30768627,
        2.61666502,  2.10952635,  2.29607613,  2.75062224,  1.93701461])

In [23]:
label[0]

0

In [24]:
print(feature[0])
print(data['target_names'][label[19]])

[ 1.09706398 -2.07333501  1.26993369  0.9843749   1.56846633  3.28351467
  2.65287398  2.53247522  2.21751501  2.25574689  2.48973393 -0.56526506
  2.83303087  2.48757756 -0.21400165  1.31686157  0.72402616  0.66081994
  1.14875667  0.90708308  1.88668963 -1.35929347  2.30360062  2.00123749
  1.30768627  2.61666502  2.10952635  2.29607613  2.75062224  1.93701461]
benign


In [25]:
df=pd.DataFrame(feature , columns = data['feature_names'])

In [26]:
df

mean radius  mean texture  ...  worst symmetry  worst fractal dimension
0       1.097064     -2.073335  ...        2.750622                 1.937015
1       1.829821     -0.353632  ...       -0.243890                 0.281190
2       1.579888      0.456187  ...        1.152255                 0.201391
3      -0.768909      0.253732  ...        6.046041                 4.935010
4       1.750297     -1.151816  ...       -0.868353                -0.397100
..           ...           ...  ...             ...                      ...
564     2.110995      0.721473  ...       -1.360158                -0.709091
565     1.704854      2.085134  ...       -0.531855                -0.973978
566     0.702284      2.045574  ...       -1.104549                -0.318409
567     1.838341      2.336457  ...        1.919083                 2.219635
568    -1.808401      1.221792  ...       -0.048138                -0.751207

[569 rows x 30 columns]

In [27]:
#500 Training

X_train=feature[:500]
Y_train=label[:500]

#35 Validation

X_val=feature[500:535]
Y_val=label[500:535]


#34 Testing

X_test=feature[535:]
Y_test=label[535:]





In [28]:
X_train.shape

(500, 30)

In [29]:
#neural network

In [30]:
model = Sequential()

model.add(Dense(15, activation = 'relu' , input_dim = 30))  #each tumor is having 30 values as input and one value as output

# activation function :it tells whether the neuron should get activated or not

model.add(Dense(15, activation = 'relu'))


model.add(Dense(15, activation = 'relu'))

model.add(Dense(1, activation = 'sigmoid'))
#activation fun:sigmoid becuase we want the values between 1 and 0
#dense:neural with one dimension

model.compile( loss='binary_crossentropy' , optimizer='adam' , metrics=['accuracy'])


In [79]:
model.fit(X_train , Y_train , batch_size=1, epochs = 5 , validation_data=(X_val,Y_val))

Epoch 1/5
500/500 [==============================] - 1s 2ms/step - loss: 0.0144 - accuracy: 0.9940 - val_loss: 0.7064 - val_accuracy: 0.8857
Epoch 2/5
500/500 [==============================] - 1s 2ms/step - loss: 0.0342 - accuracy: 0.9940 - val_loss: 0.8993 - val_accuracy: 0.9143
Epoch 3/5
500/500 [==============================] - 1s 2ms/step - loss: 0.0045 - accuracy: 0.9980 - val_loss: 0.6400 - val_accuracy: 0.9143
Epoch 4/5
500/500 [==============================] - 1s 2ms/step - loss: 1.0667e-04 - accuracy: 1.0000 - val_loss: 0.6463 - val_accuracy: 0.9143
Epoch 5/5
500/500 [==============================] - 1s 2ms/step - loss: 8.3005e-05 - accuracy: 1.0000 - val_loss: 0.6564 - val_accuracy: 0.9143


In [80]:
model.evaluate(X_test , Y_test)

2/2 [==============================] - 0s 6ms/step - loss: 0.0933 - accuracy: 0.9706


[0.09325234591960907, 0.970588207244873]

In [ ]:
#prediction

In [46]:
# sample = X_test[10]

In [34]:
# sample.shape

(30,)

In [47]:
# sample

array([-0.14407806,  0.91694624, -0.19684934, -0.23233219, -0.27756523,
       -0.6987597 , -0.741488  , -0.6316726 , -0.53894726, -0.67869351,
       -0.21356438,  0.21617286, -0.39605381, -0.20015129, -0.39100882,
       -0.25084001, -0.38739725, -0.44317904,  0.03967757, -0.45840426,
       -0.19034815,  0.55574951, -0.28836304, -0.26506358, -0.47205092,
       -0.65245698, -0.80257043, -0.65270672, -0.41860997, -0.7988643 ])

In [48]:
# sample =np.reshape(sample,(1,30))

In [50]:
# sample.shape

(1, 30)

In [51]:
# if model.predict(sample)[0][0] >0.5:
#   print('benign')
# else:
#   print('malignant')  

benign


In [53]:
# Y_test[10]

1

In [81]:
for i in range(10):

  sample=X_test[i]
  sample=np.reshape(sample,(1,30))

  if model.predict(sample)[0][0]>0.5:
    print("Predicted Value:Benign")
  else:
    print("Predicted Value:Malignant")

  if Y_test[i]==1:
    print("Actual Value:Benign")
  else:
    print("Actual Value:Malignant")      

Predicted Value:Malignant
Actual Value:Malignant
Predicted Value:Benign
Actual Value:Malignant
Predicted Value:Benign
Actual Value:Benign
Predicted Value:Benign
Actual Value:Benign
Predicted Value:Benign
Actual Value:Benign
Predicted Value:Benign
Actual Value:Benign
Predicted Value:Benign
Actual Value:Benign
Predicted Value:Benign
Actual Value:Benign
Predicted Value:Benign
Actual Value:Benign
Predicted Value:Benign
Actual Value:Benign
